server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/devbeekei/spring-cloud-config
          default-label: main
        encrypt:
          enabled: false

encrypt:
  key: devbeekei-encrypt-key